# Generated by Django 4.0.3 on 2022-03-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.IntegerField()),
                ('host', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('num_guests', models.IntegerField()),
                ('num_beds', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('property_type', models.CharField(max_length=64)),
                ('amenities', models.CharField(max_length=64)),
                ('house_rules', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_id', models.IntegerField()),
                ('apartment_id', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guest', models.CharField(max_length=64)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('since', models.DateField(auto_now_add=True)),
                ('country', models.CharField(max_length=32)),
                ('credit_card_type', models.CharField(max_length=16)),
                ('credit_card_no', models.CharField(max_length=16)),
            ],
        ),
    ]
